name: "Submit to Web Store"
on:
  workflow_dispatch:
  release:
    types: [published]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the extension
        run: npm run build
        env:
          PLASMO_PUBLIC_SUPABASE_URL: ${{ secrets.PLASMO_PUBLIC_SUPABASE_URL }}
          PLASMO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PLASMO_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Package the extension into a zip artifact
        run: npm run package

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-package
          path: build/chrome-mv3-prod.zip
          retention-days: 5

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip

      - name: Update GitHub Release with artifacts
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/chrome-mv3-prod.zip
            build/firefox-mv3-prod.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
